version = 1

[[annotations]]
path = "data/*.jpg"
SPDX-FileCopyrightText = "2025 Bart van de Lint"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "data/*.png"
SPDX-FileCopyrightText = "2025 Bart van de Lint"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "data/*.obj"
SPDX-FileCopyrightText = "2025 Bart van de Lint"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "data/*.csv"
SPDX-FileCopyrightText = "2025 Bart van de Lint"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "data/*.dat"
SPDX-FileCopyrightText = "2025 Bart van de Lint"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = ".gitignore"
SPDX-FileCopyrightText = "2025 Bart van de Lint"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "data/*.yaml"
SPDX-FileCopyrightText = "2025 Uwe Fechner"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "Project.toml"
SPDX-FileCopyrightText = "2025 Bart van de Lint"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "README.md"
SPDX-FileCopyrightText = "2025 Bart van de Lint"
SPDX-License-Identifier = "MPL-2.0"

